apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofprep2-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: dofprep2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dofprep2
    spec:
      containers:
      - name: app-cont
        image: kkostadinov9/dofprep2:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dofprep2-svc
  labels:
    app: dofprep2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: dofprep2
