apiVersion: apps/v1
kind: Deployment
metadata:
  name: role-nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: role-nginx
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: role-nginx
    spec:
      containers:
      - name: role-nginx
        image: kkostadinov9/nginxprep:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /site
          subPath: app/
          name: app
      volumes:
      - name: app
        gitRepo:
          repository: "https://github.com/kkostadinov9/dofappPrep2.git"
          revision: "main"
          directory: .
      
---
apiVersion: v1
kind: Service
metadata:
  name: role-nginx
  labels:
    app: role-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: role-nginx
